name: Test Miniray

on:
  workflow_dispatch: {}
  pull_request: { branches: [] }
  push: { branches: [ master ] }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  COMPOSE_PROJECT_NAME: miniray-${{ github.run_id }}

jobs:
  test:
    name: Test Miniray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./tests/run_tests.sh
